export const DEMO_CATEGORIES = [
  {
    id: "cat_event",
    name: "Etkinlik & Organizasyon",
    slug: "etkinlik-organizasyon",
    description: "Sandalye, Masa, Çadır, Sahne & Ses sistemleri",
    commissionRate: 10.0,
  },
  {
    id: "cat_fuar",
    name: "Fuar & Stand",
    slug: "fuar-stand",
    description: "4K TV, LED Ekran, Stand Mobilyası",
    commissionRate: 10.0,
  },
  {
    id: "cat_mutfak",
    name: "Endüstriyel Mutfak",
    slug: "endustriyel-mutfak",
    description: "Fritöz, Izgara, Sanayi Buzdolabı",
    commissionRate: 12.0,
  },
  {
    id: "cat_tech",
    name: "Teknoloji",
    slug: "teknoloji",
    description: "Laptop, Tablet, Lazer Projeksiyon",
    commissionRate: 8.0,
  },
  {
    id: "cat_ofis",
    name: "Ofis & Toplantı",
    slug: "ofis",
    description: "Çalışma Masası, Ergonomik Koltuk",
    commissionRate: 10.0,
  },
  {
    id: "cat_teknik",
    name: "Teknik & Operasyon",
    slug: "teknik-operasyon",
    description: "Süper Sessiz Jeneratör, Isıtıcı, Fan",
    commissionRate: 10.0,
  },
];

export const DEMO_COMPANIES = [
  {
    id: "comp_abc",
    name: "ABC Organizasyon A.Ş.",
    email: "operasyon@abcorganizasyon.com",
    taxNumber: "1234567890",
    taxOffice: "Maslak VD",
    city: "İstanbul",
    address: "Maslak Mah. Büyükdere Cad. No: 122/A Sarıyer",
    status: "VERIFIED",
    companyType: "CORPORATE",
    supplierProfile: null,
  },
  {
    id: "comp_mega",
    name: "Mega Event Ekipmanları Ltd.",
    email: "info@megaevent.com",
    taxNumber: "9876543210",
    taxOffice: "Mecidiyeköy VD",
    city: "İstanbul",
    address: "Seyrantepe Sanayi Mah. No: 44 Kağıthane",
    status: "VERIFIED",
    companyType: "SUPPLIER",
    supplierProfile: {
      isVerified: true,
      rating: 4.9,
      reviewCount: 38,
      completedRentals: 142,
      description: "İstanbul içi geniş envanterli kurumsal etkinlik ve organizasyon ekipmanları tedarikçisi.",
    },
  },
  {
    id: "comp_pro",
    name: "Pro Kiralama & Sahne Sistemleri A.Ş.",
    email: "kiralama@prokiralama.com",
    taxNumber: "5544332211",
    taxOffice: "Kadıköy VD",
    city: "İstanbul",
    address: "Batı Ataşehir Barbaros Mah. No: 88 Ataşehir",
    status: "VERIFIED",
    companyType: "SUPPLIER",
    supplierProfile: {
      isVerified: true,
      rating: 4.8,
      reviewCount: 29,
      completedRentals: 96,
      description: "Profesyonel fuar, sahne ve etkinlik kiralama çözümleri.",
    },
  },
];

export const DEMO_PRODUCTS = [
  {
    id: "prod_chair_mega",
    name: "Tiffany Napolyon Beyaz Sandalye (Düğün & Konferans)",
    description: "Yüksek mukavemetli polipropilen gövde, ergonomik minderli kurumsal etkinlik sandalyesi.",
    supplierCompanyId: "comp_mega",
    categoryId: "cat_event",
    category: DEMO_CATEGORIES[0],
    supplierCompany: DEMO_COMPANIES[1],
    totalStock: 600,
    dailyPrice: 45,
    weeklyPrice: 200,
    monthlyPrice: 650,
    estimatedPurchaseCost: 850,
    depositType: "PERCENTAGE",
    depositPercent: 10,
    deliveryFee: 1200,
    setupFee: 600,
    city: "İstanbul",
    condition: "EXCELLENT",
    minRentalDays: 1,
    images: [{ url: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80" }],
    volumeDiscounts: [
      { minQuantity: 50, maxQuantity: 99, discountPercent: 5 },
      { minQuantity: 100, maxQuantity: 499, discountPercent: 10 },
      { minQuantity: 500, maxQuantity: null, discountPercent: 15 },
    ],
  },
  {
    id: "prod_chair_pro",
    name: "Lake Ahşap Katlanır Sandalye (Etkinlik Serisi)",
    description: "Doğal kayın ağacından lake cilalı, iç ve dış mekan toplantı sandalyesi.",
    supplierCompanyId: "comp_pro",
    categoryId: "cat_event",
    category: DEMO_CATEGORIES[0],
    supplierCompany: DEMO_COMPANIES[2],
    totalStock: 800,
    dailyPrice: 50,
    weeklyPrice: 220,
    monthlyPrice: 700,
    estimatedPurchaseCost: 950,
    depositType: "PERCENTAGE",
    depositPercent: 10,
    deliveryFee: 1500,
    setupFee: 750,
    city: "İstanbul",
    condition: "NEW",
    minRentalDays: 1,
    images: [{ url: "https://images.unsplash.com/photo-1503602642458-232111445657?w=800&q=80" }],
    volumeDiscounts: [
      { minQuantity: 100, maxQuantity: 499, discountPercent: 8 },
      { minQuantity: 500, maxQuantity: null, discountPercent: 12 },
    ],
  },
  {
    id: "prod_tv_65",
    name: "Samsung 65 inç 4K UHD Smart TV & Yüksek Ayaklı Stand",
    description: "Fuar ve stand sunumları için 4K UHD ekran, tekerlekli şık zemin standı ve HDMI kablo kiti dahil.",
    supplierCompanyId: "comp_pro",
    categoryId: "cat_fuar",
    category: DEMO_CATEGORIES[1],
    supplierCompany: DEMO_COMPANIES[2],
    totalStock: 50,
    dailyPrice: 1200,
    weeklyPrice: 5000,
    monthlyPrice: 14000,
    estimatedPurchaseCost: 38000,
    depositType: "PERCENTAGE",
    depositPercent: 15,
    deliveryFee: 800,
    setupFee: 400,
    city: "İstanbul",
    condition: "NEW",
    minRentalDays: 1,
    images: [{ url: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&q=80" }],
    volumeDiscounts: [
      { minQuantity: 5, maxQuantity: 10, discountPercent: 10 },
      { minQuantity: 11, maxQuantity: null, discountPercent: 20 },
    ],
  },
  {
    id: "prod_table_round",
    name: "180 cm Banket Yuvarlak Masa (10 Kişilik)",
    description: "Katlanır metal ayaklı dayanıklı organizasyon ve toplantı masası.",
    supplierCompanyId: "comp_mega",
    categoryId: "cat_event",
    category: DEMO_CATEGORIES[0],
    supplierCompany: DEMO_COMPANIES[1],
    totalStock: 300,
    dailyPrice: 180,
    weeklyPrice: 800,
    monthlyPrice: 2400,
    estimatedPurchaseCost: 3200,
    depositType: "PERCENTAGE",
    depositPercent: 10,
    deliveryFee: 1000,
    setupFee: 500,
    city: "İstanbul",
    condition: "EXCELLENT",
    minRentalDays: 1,
    images: [{ url: "https://images.unsplash.com/photo-1530629013299-6cb10d168419?w=800&q=80" }],
    volumeDiscounts: [
      { minQuantity: 20, maxQuantity: 49, discountPercent: 5 },
      { minQuantity: 50, maxQuantity: null, discountPercent: 15 },
    ],
  },
  {
    id: "prod_fryer_double",
    name: "Öztiryakiler Çift Havuzlu 2x10 Lt Elektrikli Fritöz",
    description: "380V Sanayi tipi paslanmaz çelik profesyonel catering ve mutfak fritözü.",
    supplierCompanyId: "comp_mega",
    categoryId: "cat_mutfak",
    category: DEMO_CATEGORIES[2],
    supplierCompany: DEMO_COMPANIES[1],
    totalStock: 40,
    dailyPrice: 650,
    weeklyPrice: 2800,
    monthlyPrice: 8500,
    estimatedPurchaseCost: 26000,
    depositType: "PERCENTAGE",
    depositPercent: 20,
    deliveryFee: 600,
    setupFee: 300,
    city: "İstanbul",
    condition: "EXCELLENT",
    minRentalDays: 1,
    images: [{ url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80" }],
    volumeDiscounts: [],
  },
  {
    id: "prod_generator_100",
    name: "Aksa 100 kVA Süper Sessiz Dizel Jeneratör (Kabinli)",
    description: "Açık hava festivalleri ve şantiyeler için otomatik transfer panolu, kesintisiz jeneratör.",
    supplierCompanyId: "comp_pro",
    categoryId: "cat_teknik",
    category: DEMO_CATEGORIES[5],
    supplierCompany: DEMO_COMPANIES[2],
    totalStock: 10,
    dailyPrice: 5500,
    weeklyPrice: 24000,
    monthlyPrice: 70000,
    estimatedPurchaseCost: 450000,
    depositType: "FIXED",
    depositFixed: 15000,
    deliveryFee: 3500,
    setupFee: 2000,
    city: "İstanbul",
    condition: "EXCELLENT",
    minRentalDays: 1,
    images: [{ url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80" }],
    volumeDiscounts: [],
  },
];

export const DEMO_RFQS = [
  {
    id: "rfq_demo_1",
    rfqNumber: "RFQ-2026-0001",
    title: "10-12 Ekim Lütfi Kırdar Kurumsal Kongre Ekipman Talebi",
    tenantCompanyId: "comp_abc",
    tenantCompany: DEMO_COMPANIES[0],
    city: "İstanbul",
    venueAddress: "Lütfi Kırdar Kongre ve Sergi Sarayı, Harbiye, Şişli / İstanbul",
    startDate: "2026-10-10",
    endDate: "2026-10-12",
    status: "OPEN",
    createdAt: "2026-08-30T10:00:00.000Z",
    items: [
      { id: "item_1", productName: "Tiffany Sandalye", quantity: 1000, categoryId: "cat_event" },
      { id: "item_2", productName: "180 cm Yuvarlak Masa", quantity: 100, categoryId: "cat_event" },
      { id: "item_3", productName: "65 inç 4K TV & Stand", quantity: 20, categoryId: "cat_fuar" },
    ],
    quotes: [
      {
        id: "quote_mega",
        quoteNumber: "QTE-2026-0001",
        supplierCompany: DEMO_COMPANIES[1],
        totalAmount: 32000,
        deliveryFee: 1200,
        setupFee: 600,
        depositTotal: 3500,
        validDays: 7,
        status: "SUBMITTED",
        items: [
          { id: "qit_1", rfqItemId: "item_1", offeredQuantity: 600, unitDailyPrice: 45, totalPrice: 27000 },
        ],
      },
      {
        id: "quote_pro",
        quoteNumber: "QTE-2026-0002",
        supplierCompany: DEMO_COMPANIES[2],
        totalAmount: 24000,
        deliveryFee: 1500,
        setupFee: 750,
        depositTotal: 3000,
        validDays: 7,
        status: "SUBMITTED",
        items: [
          { id: "qit_2", rfqItemId: "item_1", offeredQuantity: 400, unitDailyPrice: 50, totalPrice: 20000 },
        ],
      },
    ],
  },
];

export const DEMO_ORDERS = [
  {
    id: "ord_demo_1",
    orderNumber: "ORD-2026-0001",
    tenantCompanyId: "comp_abc",
    tenantCompany: DEMO_COMPANIES[0],
    supplierCompanyId: "comp_mega",
    supplierCompany: DEMO_COMPANIES[1],
    startDate: "2026-10-10",
    endDate: "2026-10-12",
    status: "CONFIRMED",
    subtotal: 27000,
    discountAmount: 2700,
    deliveryFee: 1200,
    setupFee: 600,
    vatAmount: 5220,
    depositAmount: 3500,
    grandTotal: 31320,
    platformCommissionFee: 2610,
    supplierPayout: 23490,
    deliveryAddress: "Lütfi Kırdar Kongre Merkezi, Harbiye, İstanbul",
    items: [
      { id: "ord_it_1", productId: "prod_chair_mega", product: DEMO_PRODUCTS[0], quantity: 600, unitDailyPrice: 45, totalPrice: 24300 },
    ],
    damageClaims: [],
    handoverProtocols: [],
  },
];
